### ISSUE TITLE
ibgConnect() clientId is being ignored

### ISSUE THREAD

**Issue by Javdat** [braverock/PerformanceAnalytics#58] opened 2016-07-25 16:01 UTC
When connecting to the IB gateway with ibgConnect(), cleintId seems to be ignored.

`> tws <- ibgConnect(clientId = 6)`

Gateaway logs show:
`Client ID is 0`

![screen shot 2016-07-25 at 5 55 27 pm](https://cloud.githubusercontent.com/assets/19429297/17107910/8a84d1d0-5291-11e6-9da2-67bb0dd62c79.png)

This may cause problems when connecting with several instances to the same gateway:
![screen shot 2016-07-25 at 5 56 28 pm](https://cloud.githubusercontent.com/assets/19429297/17107933/a527856e-5291-11e6-8347-bc95a1c87b13.png)

This leads to continues rejection of the "same" cliend IDs by several by the gateaway and eventual crash of the gateway. 

Sometimes, after the error, random client ID is assigned:
![screen shot 2016-07-25 at 5 56 39 pm](https://cloud.githubusercontent.com/assets/19429297/17107952/b527fb88-5291-11e6-902e-e3c09f5f1ad1.png)

**Comment by joshuaulrich** [comment] 2016-07-25 16:06
What does this have to do with PerformanceAnalytics?

**Comment by Javdat** [comment] 2016-07-25 16:06
I am sorry.... I misclicked the github. Delete this.

**Comment by joshuaulrich** [comment] 2016-07-25 16:07
And this is a duplicate of an already existing issue on the IBrokers GitHub account.

**Comment by Javdat** [comment] 2016-07-25 16:07
Yeap, have found it. Thank you

**Closed** 2016-07-25 16:06 UTC
