### ISSUE TITLE
charts.PerformanceSummary fails

### ISSUE THREAD

**Issue by erolbicero** [braverock/PerformanceAnalytics#82] opened 2017-12-17 19:04 UTC
When I run `charts.PerformanceSummary` on the github version, it fails.

Here's my `sessionInfo()`

```r
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/lapack/liblapack.so.3.0

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C               LC_TIME=en_CA.UTF-8       
 [4] LC_COLLATE=en_CA.UTF-8     LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8   
 [7] LC_PAPER=en_CA.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] quantmod_0.4-12            TTR_0.23-2                 PerformanceAnalytics_1.5.1
[4] xts_0.10-1                 zoo_1.8-0                 

loaded via a namespace (and not attached):
 [1] quadprog_1.5-5  lattice_0.20-35 digest_0.6.12   withr_2.1.0     grid_3.4.3      R6_2.2.2       
 [7] git2r_0.19.0    httr_1.3.1      curl_3.1        devtools_1.13.4 tools_3.4.3     compiler_3.4.3 
[13] memoise_1.1.0  
```

Here's an MRE:

```r
#devtools::install_github("braverock/PerformanceAnalytics")

library(xts)
library(PerformanceAnalytics)
library(quantmod)


getSymbols("SPY")

charts.PerformanceSummary(Return.calculate(SPY$SPY.Adjusted))
```

Here's the error output:

```r
> charts.PerformanceSummary(Return.calculate(SPY$SPY.Adjusted))
Error in diff(x) * c(Env$pad1, Env$pad3) : 
  non-numeric argument to binary operator
In addition: Warning messages:
1: In chart.TimeSeries.base(R, auto.grid, xaxis, yaxis, yaxis.right,  :
  The auto.grid argument of chart.TimeSeries has been deprecated, and may be removed in a future release, see help('chart.TimeSeries') for more information.
2: In chart.TimeSeries.base(R, auto.grid, xaxis, yaxis, yaxis.right,  :
  The las argument of chart.TimeSeries has been deprecated, and may be removed in a future release, see help('chart.TimeSeries') for more information.
3: In chart.TimeSeries.base(R, auto.grid, xaxis, yaxis, yaxis.right,  :
  The ylab argument of chart.TimeSeries has been deprecated, and may be removed in a future release, see help('chart.TimeSeries') for more information.
4: In chart.TimeSeries.base(R, auto.grid, xaxis, yaxis, yaxis.right,  :
  The xlab argument of chart.TimeSeries has been deprecated, and may be removed in a future release, see help('chart.TimeSeries') for more information.
5: In chart.TimeSeries.base(R, auto.grid, xaxis, yaxis, yaxis.right,  :
  The cex.axis argument of chart.TimeSeries has been deprecated, and may be removed in a future release, see help('chart.TimeSeries') for more information.
6: In chart.TimeSeries.base(R, auto.grid, xaxis, yaxis, yaxis.right,  :
  The cex.lab argument of chart.TimeSeries has been deprecated, and may be removed in a future release, see help('chart.TimeSeries') for more information.
7: In chart.TimeSeries.base(R, auto.grid, xaxis, yaxis, yaxis.right,  :
  The cex.labels argument of chart.TimeSeries has been deprecated, and may be removed in a future release, see help('chart.TimeSeries') for more information.
8: In chart.TimeSeries.base(R, auto.grid, xaxis, yaxis, yaxis.right,  :
  The cex.main argument of chart.TimeSeries has been deprecated, and may be removed in a future release, see help('chart.TimeSeries') for more information.
9: In chart.TimeSeries.base(R, auto.grid, xaxis, yaxis, yaxis.right,  :
  The xaxis.labels argument of chart.TimeSeries has been deprecated, and may be removed in a future release, see help('chart.TimeSeries') for more information.
10: In structure(ylim, fixed = fixed) :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.
```

**Comment by joshuaulrich** [comment] 2017-12-17 19:14
This is caused by https://github.com/joshuaulrich/xts/issues/220

**Comment by joshuaulrich** [comment] 2017-12-20 17:36
Closing, as this is now fixed in xts_0.10-1 and was not specific to `charts.PerformanceSummary()` anyway.

**Closed by joshuaulrich** 2017-12-20 17:36 UTC
