### ISSUE TITLE
charting crashes on intraday data

### ISSUE THREAD

**Issue by bnleavitt** [braverock/PerformanceAnalytics#96] opened 2018-05-09 16:43 UTC
See the following link:

https://stackoverflow.com/questions/50026611/error-in-xy-coordsx-y-x-and-y-lengths-differ-charts-performancesummary

The code works correctly in version 1.4.3541

**Comment by rossb34** [comment] 2018-05-09 18:02
Here is a minimal reproducible example of the problem using plot.xts the way that 
charts.PerformanceSummary and the chart.* functions do the plotting.

```
library(xts)
x <- xts(c(.05,.01,-0.1),as.POSIXct(c('2018-02-28','2018-03-29','2018-04-24')))
xx <- x
time(xx) = as.Date(time(xx))#https://github.com/braverock/PerformanceAnalytics/blob/242f5262301431980edb258d4068f64c57968f0e/R/chart.BarVaR.R#L181
plot(cumsum(x))
addSeries(xx, type = "h")#fail
```

The problem is that `x` has a `tzone` attribute of "" and casting the index of `x` to `Date` adds a `tzone` attribute of "UTC".
```
> .index(x)
[1] 1519797600 1522299600 1524546000
attr(,"tzone")
[1] ""
attr(,"tclass")
[1] "POSIXct" "POSIXt" 
> .index(xx)
[1] 1519776000 1522281600 1524528000
attr(,"tclass")
[1] "Date"
attr(,"tzone")
[1] "UTC"
> merge(x, xx)
                        x    xx
2018-02-27 18:00:00    NA  0.05
2018-02-28 00:00:00  0.05    NA
2018-03-28 19:00:00    NA  0.01
2018-03-29 00:00:00  0.01    NA
2018-04-23 19:00:00    NA -0.10
2018-04-24 00:00:00 -0.10    NA
```

**Comment by rossb34** [comment] 2018-05-09 18:15
Minimal example from the SO link can be fixed by specifying `tz` or by creating an index with the class of `Date`. Both of these work.

```
library(PerformanceAnalytics)
charts.PerformanceSummary(xts(c(.05,.01,-0.1),as.POSIXct(c('2018-02-28','2018-03-29','2018-04-24'), tz = "UTC")))
charts.PerformanceSummary(xts(c(.05,.01,-0.1),as.Date(c('2018-02-28','2018-03-29','2018-04-24'))))
```

We should also consider removing ` time(x) = as.Date(time(x))` in `chart.BarVaR`. The [blame](https://github.com/braverock/PerformanceAnalytics/blame/242f5262301431980edb258d4068f64c57968f0e/R/chart.BarVaR.R#L181) shows that this was added 10 years ago due to an issue with `merge.zoo`. It is unclear what the specific issue was or if this is still an issue.

**Comment by braverock** [comment] 2018-06-14 11:47
I've just merged a fix.  Please re-install from github and test.  This resolves the issue in our testing.

**Closed** 2018-06-14 11:47 UTC
