### ISSUE TITLE
SharpeRatio annualize = TRUE fails for method 'StdDev'

### ISSUE THREAD

**Issue by Javdat** [braverock/PerformanceAnalytics#66] opened 2017-01-16 14:22 UTC
`SharpeRatio` ratio function is supposedly preferred to `SharpeRatio.annualized()` as it already incorporates the same functionality via parameter annualize = TRUE.

However, currently, SharpeRatio fails  when parameter `annualize = TRUE` is passed and FUN includes "StdDev" (original Sharpe):

```
data(managers)
# without annualize
SharpeRatio(managers[,1:9], Rf = managers[,10,drop=FALSE])
# with annualize
SharpeRatio(managers[,1:9], Rf = managers[,10,drop=FALSE], annualize = TRUE)
```

```
# with annualize

Error in FUNCT(R = R, p = p, ... = ..., invert = FALSE) : 
  'x' needs to be timeBased or xtsible, or scale must be specified.
```

Even though R is xtsible 
```
> xtsible(managers[,1:9])
[1] TRUE
> xtsible( managers[,10,drop=FALSE])
[1] TRUE
```

I think this is connected to the fact that `match.fun("StdDev.annualized")` takes `x` as an argument rather than `R` that is being passed to it via `FUNCT(R = R, p = p, ... = ..., invert = FALSE)`

**Comment by Javdat** [comment] 2017-02-14 19:44
I think the problem lies in the fact that `scale` is not being passed to `StdDev.annualized`.

`sra` is defined here (lines 25-43):

```
  sra <- function(R, ..., Rf, p, FUNC) {
    if (FUNC == "StdDev") 
      FUNC = "StdDev.annualized"
    FUNCT <- match.fun(FUNC)
    xR = Return.excess(R, Rf)
    SRA = Return.annualized(xR)/FUNCT(R = R, p = p, ... = ..., 
                                      invert = FALSE)
    SRA
  }
```

later `sra` is called (lines 55-57):

```
      if (annualize) 
        result[i, ] = sapply(R, FUN = sra, Rf = Rf, p = p, 
                             FUNC = FUNCT, ...)
```

Thus, `scale` is not passed.

I propose to modify line 55- 57 to:

```
      if (annualize) 
        result[i, ] = sapply(R, FUN = sra, Rf = Rf, p = p, 
                             FUNC = FUNCT, scale = scale, ...)
```

**Comment by joshuaulrich** [comment] 2017-02-14 19:58
Lines 55-57 are comments.  It appears you're referencing the source when you print the function definition from the R console.  It's better to reference the lines in the actual source code, since that's what needs to change.  Looks like you're referring to [lines 159-160](https://github.com/braverock/PerformanceAnalytics/blob/de6c0f60ba84df023dbed1411b3d9fc8c1c90aed/R/SharpeRatio.R#L159-L160).

**Comment by Javdat** [comment] 2017-02-14 20:08
Yes, you are right. Silly mistake by me. Thank you.

**Comment by joshuaulrich** [comment] 2017-02-14 20:11
I don't thin k the problem is that `scale` needs to be added to the call to `FUNCT` (`StdDev.annualized`).  The problem is that the arguments passed to the call to `FUNCT` match the formals for `StdDev`, but not `StdDev.annualized`.  The call to `FUNCT` is:

```r
FUNCT(R=R, p=p, ...=..., invert=FALSE)
```

But the formal arguments of `StdDev.annualized` do not include `R`, `p`, or `invert`.

```r
Browse[3]> args(StdDev.annualized)
function (x, scale = NA, ...) 
NULL
Browse[3]> args(StdDev)
function (R, ..., clean = c("none", "boudt", "geltner"), portfolio_method = c("single", 
    "component"), weights = NULL, mu = NULL, sigma = NULL, use = "everything", 
    method = c("pearson", "kendall", "spearman")) 
NULL
```

So, instead, it looks like the branching in `sra` needs to be modified.  Thanks for digging in to the issue.  It certainly helped point me in the right direction in order to find the root cause faster.

**Comment by joshuaulrich** [comment] 2017-02-15 16:24
Fixed in https://github.com/braverock/PerformanceAnalytics/commit/2c6810ef00f812d0ab138729164ab721ef5d714d.

**Closed by joshuaulrich** 2017-02-15 16:24 UTC
Labels: bug
