### ISSUE TITLE
chart.RelativePerformance warnings

### ISSUE THREAD

**Issue by evelynmitchell** [braverock/PerformanceAnalytics#40] opened 2016-06-23 04:38 UTC
chart.RelativePerformance(managers[,1], managers[,9])
Warning messages:
1: In chart.TimeSeries.base(R, auto.grid, xaxis, yaxis, yaxis.right,  :
  The auto.grid argument of chart.TimeSeries has been deprecated, and may be removed in a future release, see help('chart.TimeSeries') for more information.
2: In chart.TimeSeries.base(R, auto.grid, xaxis, yaxis, yaxis.right,  :
  The las argument of chart.TimeSeries has been deprecated, and may be removed in a future release, see help('chart.TimeSeries') for more information.
3: In chart.TimeSeries.base(R, auto.grid, xaxis, yaxis, yaxis.right,  :
  The ylab argument of chart.TimeSeries has been deprecated, and may be removed in a future release, see help('chart.TimeSeries') for more information.
4: In chart.TimeSeries.base(R, auto.grid, xaxis, yaxis, yaxis.right,  :
  The xlab argument of chart.TimeSeries has been deprecated, and may be removed in a future release, see help('chart.TimeSeries') for more information.
5: In chart.TimeSeries.base(R, auto.grid, xaxis, yaxis, yaxis.right,  :
  The cex.axis argument of chart.TimeSeries has been deprecated, and may be removed in a future release, see help('chart.TimeSeries') for more information.
6: In chart.TimeSeries.base(R, auto.grid, xaxis, yaxis, yaxis.right,  :
  The cex.lab argument of chart.TimeSeries has been deprecated, and may be removed in a future release, see help('chart.TimeSeries') for more information.
7: In chart.TimeSeries.base(R, auto.grid, xaxis, yaxis, yaxis.right,  :
  The cex.labels argument of chart.TimeSeries has been deprecated, and may be removed in a future release, see help('chart.TimeSeries') for more information.
8: In chart.TimeSeries.base(R, auto.grid, xaxis, yaxis, yaxis.right,  :
  The cex.main argument of chart.TimeSeries has been deprecated, and may be removed in a future release, see help('chart.TimeSeries') for more information.
9: In chart.TimeSeries.base(R, auto.grid, xaxis, yaxis, yaxis.right,  :
  The xaxis.labels argument of chart.TimeSeries has been deprecated, and may be removed in a future release, see help('chart.TimeSeries') for more information.

**Comment by joshuaulrich** [comment] 2016-06-23 12:53
Closing as duplicate of #35.

**Closed by joshuaulrich** 2016-06-23 12:53 UTC
Labels: duplicate
